# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('table_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('date', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('effective_date', models.DateField()),
                ('when_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.Table'),
        ),
    ]
