# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='effective_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='table_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='date',
        ),
    ]
