# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_auto_20161113_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='code',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='table_id',
            new_name='table',
        ),
    ]
