# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_auto_20161113_0717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('currency', 'table')]),
        ),
    ]
