CODE_TO_COUNTRY = {
    'THB': 'Tajlandia',
    'USD': 'Stany Zjednoczone',
    'AUD': 'Australia',
    'HKD': 'Hongkong',
    'CAD': 'Kanada',
    'NZD': 'Nowa Zelandia',
    'SGD': 'Singapur',
    'EUR': 'Unia Europejska',
    'HUF': 'Węgry',
    'CHF': 'Szwajcaria',
    'GBP': 'Wielka Brytania',
    'UAH': 'Ukraina',
    'JPY': 'Japonia',
    'CZK': 'Czechy',
    'DKK': 'Dania',
    'ISK': 'Islandia',
    'NOK': 'Norwegia',
    'SEK': 'Szwecja',
    'HRK': 'Chorwacja',
    'RON': 'Rumunia',
    'BGN': 'Bułgaria',
    'TRY': 'Turcja',
    'ILS': 'Izrael',
    'CLP': 'Chile',
    'PHP': 'Filipiny',
    'MXN': 'Meksyk',
    'ZAR': 'Republika Południowej Afryki',
    'BRL': 'Brazylia',
    'MYR': 'Malezja',
    'RUB': 'Rosja',
    'IDR': 'Indonezja',
    'INR': 'Indie',
    'KRW': 'Korea Południowa',
    'CNY': 'Chiny',
    'XDR': 'SDR (MFW)'
    }
