# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161213_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 12, 13, 21, 0, 4, 412518, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
