# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20161223_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
